name: CSMC
main: dev.danablend.counterstrike.CounterStrike
author: danablend, barpec12, tontito007
folia-supported: true
version: 1.7.6
api-version: 1.19
depend: [QualityArmory]
softdepend: [IACenter,PlaceholderAPI]
commands:
  csmc:
    description: Admin command for the CounterStrike plugin.
    aliases: [cs, counterstrike]
    permission: 'cs.admin'
    permission-message: 'ยง4You do not have permission to do that!'

#  test:
#    description: Test commands for the plugin.
#    permission: 'cs.admin'
#    permission-message: 'ยง4You do not have permission to do that!'